kind: Service
apiVersion: v1
metadata:
  name: archiva-internal
  labels:
    app: htk-archiva
spec:
  selector:
    app: htk-archiva
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: archiva
  labels:
    app: htk-archiva
spec:
  type: LoadBalancer
  selector:
    app: htk-archiva
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP  
