apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: htk-artifactory
spec:
  selector:
    matchLabels:
      app: htk-artifactory
  replicas: 1
  template:
    metadata:
      labels:
        app: htk-artifactory
    spec:
      initContainers:
        - name: init-ownership
          image: busybox
          command:
            - sh
            - -c
            - if [ $(ls -ldn /artifactory-data | awk '{ print $3 }') != 1000 ]; then chown -R 1000:1000 /artifactory-data; fi 
          volumeMounts:
            - mountPath: /artifactory-data
              name: artifactory-data
      containers:
        - name: artifactory
          image: "kgyrtkirk/htk-artifactory:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: JVM_MAX_MEM
              value: "768"
          volumeMounts:
            - mountPath: /artifactory-data
              name: artifactory-data
          resources:
            limits:
              cpu: 1500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 800Mi

      volumes:
        - name: artifactory-data
          emptyDir: {}
