apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: htk-static-address
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: jenkins
          servicePort: 8080

          