apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: htk-jenkins
spec:
  #type: ClusterIP
  type: NodePort 
  externalTrafficPolicy: Local
  #type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: htk-jenkins
