---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-internal
  labels:
    app: htk-jenkins
spec:
  type: ClusterIP
  selector:
    app: htk-jenkins
  # ensure the client ip is propagated to avoid the invalid crumb issue when using LoadBalancer (k8s >=1.7)
  #externalTrafficPolicy: Local
  ports:
    -
      name: http
      port: 8080
      protocol: TCP
    -
      name: agent
      port: 50000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: htk-jenkins
spec:
  #type: ClusterIP
  #type: NodePort 
  #externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    -
      name: http
      port: 8080
      targetPort: 8080
      protocol: TCP  
  selector:
    app: htk-jenkins
