---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  verbs: ["list", "watch", "create", "delete", "update"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pvc-htk-jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvc-role
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default
